### DISCUSSION TITLE
Showcase your template(s)

### DISCUSSION THREAD

**Discussion by bandantonio** [bandantonio/obsidian-apple-books-highlights-plugin#32] [Show and tell]
Hi guys,

My plugin provides you with great opportunity to customize the options for how you want to see the generated notes for your highlights. And I thought that it would be great for you to showcase your templates and tell a little story about why you feel so special about it. 

I will place a link to this discussion to the README file so that anyone can contribute to it. And new users who are playing around with the plugin, may find their inspiration here as well.

Let's start, I go first. Basically, I'm using the default template as it contains all the bells and whistles I expect from a Literature note. At this moment, in my Zettelkasten setup, Literature notes are temporary where all the highlights eventually dissolve in other notes and become a part of something bigger. However, I want to keep my registry of the books I've read but I'm still playing around with the format.

My template

```hbs
Title:: 📕 {{{bookTitle}}}
Author:: {{{bookAuthor}}}
Link:: [Apple Books Link](ibooks://assetid/{{bookId}})

## Annotations

Number of annotations:: {{annotations.length}}

{{#each annotations}}
----

- 📖 Chapter:: {{#if chapter}}{{{chapter}}}{{else}}N/A{{/if}}
- 🔖 Context:: {{#if contextualText}}{{{contextualText}}}{{else}}N/A{{/if}}
- 🎯 Highlight:: {{{highlight}}}
- 📝 Note:: {{#if note}}{{{note}}}{{else}}N/A{{/if}}
- 📙 Highlight Link:: {{#if highlightLocation}}[Apple Books Highlight Link](ibooks://assetid/{{../bookId}}#{{highlightLocation}}){{else}}N/A{{/if}}

{{/each}}
```

Rendered version

<img width="796" alt="template-showcase" src="https://github.com/user-attachments/assets/ea3376d5-176c-4f12-99ad-e317e5b121da">

It's your turn now! Can't wait to see your work! Don't be shy ☺️

**Comment by pseudoctor** [comment]
Thanks for providing the efficient tool. Here's two problems when I use the Template. The first is the infomation about title\author was not print in the yaml even I add "---" at the begin and the end; The second is the Chapter is always show with N/A. I don't know what's wrong with my action. I would like to change the chapter into H2, so it can form an outline for read.

I wrote with the help of gpt, but it can't work.

<img width="1208" alt="12" src="https://github.com/user-attachments/assets/3535787f-444f-4935-95a6-2ad6efdce86e">

**Reply by bandantonio** [reply]
Hi @AlexlandWang 
Thanks for your report.
> the infomation about title\author was not print in the yaml even I add "---" at the begin and the end

If you want `book`, `author`, `language`, and `link` variables to be treated as [Properties](https://help.obsidian.md/Editing+and+formatting/Properties), you need to format them properly. In you case, you can't see the title/author because there is a problem with the `link` variable that contains a Markdown link (Markdown isn't a supported type).

You can adjust your template like this:

```yaml
---
book:: {{bookTitle}}
author:: {{bookAuthor}}
language:: {{bookLanguage}}
link:: ibooks://assetid/{{bookId}}
---
```
Rendered example:

<img width="562" src="https://github.com/user-attachments/assets/b3b3e39f-c31c-4885-a952-1b9c23bcdd50">

----

> the Chapter is always show with N/A

It mostly depends on the internal semantic formatting of a particular e-book. In my collection (~60 books), I have only one book with defined chapters. Even if you can see chapters in the Table Of Contents and can navigate through them in the e-book reader, the internal structure of the e-book might not have them defined properly.

----

I also noticed that you were using the `{{#group by="chapter"}}` custom helper, which is not natively supported by Handlebars. I will think about adding support for this in the future, but for now, the grouping won't work as expected.

**Reply by pseudoctor** [reply]
Thank you for fixing my problem and detailed explaination

**Comment by banj** [comment]
Dropping by to share my template in progress! I adapted the default template by adding front matter, adding a markdown table, using @index to have collapsable sections for each highlight, and putting the highlight text in a callout. I experimented with some Dataview tables but I found I liked the markdown table better for my use case.

I also built in links to other files for the book, since the importer overwrites any changes to the imported highlights file this gives me somewhere to add thoughts and comments.

```
---
title: {{{bookTitle}}}
author: {{{bookAuthor}}}
source: ibooks://assetid/{{bookId}}
aliases: {{{bookAuthor}}}-{{{bookTitle}}}-highlights
---
# {{{bookTitle}}}
## {{{bookAuthor}}}

bookLastOpenedDate:: {{dateFormat bookLastOpenedDate "YYYY-MM-DD, HH:mm:ss"}}
references:: [[books/{{{bookAuthor}}}-{{{bookTitle}}}]]
areas:: [[Highlights]]

## Summary

Title:: {{{bookTitle}}}
Author:: {{{bookAuthor}}}
Link:: [Apple Books Link](ibooks://assetid/{{bookId}})

## Annotations

Total annotations:: {{annotations.length}}

### Table
| Creation Date | Chapter | Highlight | Note |
| ---------------- | ---------------- | ---------------- | --------- |
{{#each annotations}}| {{#if highlightCreationDate}}{{{dateFormat highlightCreationDate "YYYY-MM-DD"}}}{{else}}N/A{{/if}} | {{#if chapter}}{{{chapter}}}{{else}}N/A{{/if}} | {{{highlight}}} | {{#if note}}{{{note}}}{{else}}N/A{{/if}} |
{{/each}}

{{#each annotations}}
### {{@index}}
> [!quote]
> {{{highlight}}}

- highlightCreationDate:: {{#if highlightCreationDate}}{{{dateFormat highlightCreationDate "YYYY-MM-DD"}}}{{else}}N/A{{/if}}
- chapter:: {{#if chapter}}{{{chapter}}}{{else}}N/A{{/if}}
- context:: {{#if contextualText}}{{{contextualText}}}{{else}}N/A{{/if}}
- quoteText:: {{{highlight}}}
- note:: {{#if note}}{{{note}}}{{else}}N/A{{/if}}
- source:: {{#if highlightLocation}}[Apple Books Highlight Link](ibooks://assetid/{{../bookId}}#{{highlightLocation}}){{else}}N/A{{/if}}

{{/each}}
```

**Reply by bandantonio** [reply]
@banj It looks awesome, thanks for sharing!
I like that you're using almost 100% of the plugin's capabilities and even Handlebars's built-in helpers 😎
Please let me know about the final results once you're happy with the template.

> I also built in links to other files for the book, since the importer overwrites any changes to the imported highlights file this gives me somewhere to add thoughts and comments.

There are several possible solutions to this problem. Please check the discussion #33 for more details.

**Comment by camilogarciabotero** [comment]
Thanks for developing this extension. It suites very nice to my workflow!

Here is my template:


```md
---
title: {{{bookTitle}}}
author: {{{bookAuthor}}}
highlights: {{annotations.length}}
opened: {{dateFormat bookLastOpenedDate "YYYY-MM-DD"}}
cover: {{bookCoverUrl}}
---
## Annotations from {{{bookTitle}}}

Go to the [Book](ibooks://assetid/{{bookId}})

{{#each annotations}}
----

## [[{{dateFormat highlightCreationDate "YYYY-MM-DD"}}]]

{{#if contextualText}} > {{{contextualText}}} {{else}}> [...]{{/if}}

"{{{highlight}}}" {{#if highlightLocation}} [Highlight Link](ibooks://assetid/ {{../bookId}} # {{highlightLocation}}) {{else}}[...]{{/if}} {{#if note}} {{{note}}} {{else}}...{{/if}}

{{/each}}

```

How it looks:


![image](https://github.com/user-attachments/assets/6d64e5e0-207c-47f3-be3c-3846dedaa531)


It is also cool that as we can use the cover, I created a project view that lets me keep my books on a sort of shelf:

![image](https://github.com/user-attachments/assets/8d2aafa6-513b-4759-b3a1-2ec1301c096b)


PS: Some of my books don't have covers though, Is it possible to improve the extraction of covers or use others like in the [obsidian-book-search-plugin](https://github.com/anpigon/obsidian-book-search-plugin)?

Best.

**Reply by isdamir** [reply]
I hope the ability to extract the cover can be added.

**Reply by bandantonio** [reply]
> Some of my books don't have covers though, Is it possible to improve the extraction of covers or use others like in the [obsidian-book-search-plugin](https://github.com/anpigon/obsidian-book-search-plugin)?

@camilogarciabotero It is expected that some books don't have covers, it means that the book author didn't specify it and, as a result, this info is not stored in the database.

Adding this functionality is theoretically possible but, on the other hand, I'm not sure if it makes a lot of sense to duplicate the functionality of the existing plugin that was created with this specific purpose in mind.
@isdamir FYI ^^

**Reply by bandantonio** [reply]
@camilogarciabotero BTW, seems like your Obsidian has a lot of plugins, as the ribbon is full of icons.
Would you mind sharing your list?

**Reply by camilogarciabotero** [reply]
Sure, thanks for the answer regarding the covers. From the bottom:

Random note (core)
Markwhen (community)
Graph view (core)
Workspace (core)
Projects (community)
tldraw (community)
Voice recording (core)
Canvas (core)
Book Search (community)
Calendar (community)
Command palette (core)
Omnisearh (community)
Quick Switcher (core)
Omnivore (community)

**Reply by isdamir** [reply]
> > Some of my books don't have covers though, Is it possible to improve the extraction of covers or use others like in the [obsidian-book-search-plugin](https://github.com/anpigon/obsidian-book-search-plugin)?
> 
> @camilogarciabotero It is expected that some books don't have covers, it means that the book author didn't specify it and, as a result, this info is not stored in the database.
> 
> Adding this functionality is theoretically possible but, on the other hand, I'm not sure if it makes a lot of sense to duplicate the functionality of the existing plugin that was created with this specific purpose in mind. @isdamir FYI ^^

Hello @bandantonio , that's right. Many of my books are downloaded from Z-libary, and when opened in iBooks, they display covers. These covers should be the metadata or the first page of the books.
I understand that this feature is part of the book synchronization capabilities and is not specifically created for this function. I'm not sure if it is possible to retrieve the image through screenshots or via the iBooks API. If it is retrievable, it could be stored in the attachment folder.

**Reply by 5Net** [reply]
Have you solved the cover issue? I also downloaded the book from Z-library

**Comment by jun6lee** [comment]
```
# Annotations: {{annotations.length}}

{{#each annotations}}
{{#if (eq highlightStyle "0")}}### {{{highlight}}}
---
{{else}}
\`\`\`
{{{highlight}}}
\`\`\`
{{/if}}
{{/each}}
```

The idea with this being to make all underlines into Headings and have all the highlights as code blocks that can be copied by a click.

![CShot 2024-09-15 at 13 02 50@2x](https://github.com/user-attachments/assets/d5561449-2dab-425e-b41c-ed95074a0af6)

**Comment by jun6lee** [comment]
```
# Annotations: {{annotations.length}}

{{#each annotations}}
{{#if (eq highlightStyle "0")}}### {{{highlight}}}
---  
{{else if (eq highlightStyle "1")}}<mark style="background:rgb(175,213,151); color:#000; padding:2px;">{{{highlight}}}</mark>
{{else if (eq highlightStyle "2")}}<mark style="background:rgb(181,205,238); color:#000; padding:2px;">{{{highlight}}}</mark>
{{else if (eq highlightStyle "3")}}<mark style="background:rgb(249,213,108); color:#000; padding:2px;">{{{highlight}}}</mark>
{{else if (eq highlightStyle "4")}}<mark style="background:rgb(242,178,188); color:#000; padding:2px;">{{{highlight}}}</mark>
{{else if (eq highlightStyle "5")}}<mark style="background:rgb(214,192,238); color:#000; padding:2px;">{{{highlight}}}</mark>
{{/if}}
{{#if note}}> [!Note] {{{note}}} 
{{else}}{{/if}}
{{/each}}
```

More or less similar to the standard colour highlights template, but making the underlines as headings.

![CShot 2024-09-15 at 13 07 01@2x](https://github.com/user-attachments/assets/a8a492fd-65d2-4d1a-8d41-bcd943d7f47a)

**Comment by jun6lee** [comment]
```
---
title: {{{bookTitle}}}
author: {{{bookAuthor}}}
annotations: {{{annotations.length}}}
---
# [{{bookTitle}}](ibooks://assetid/{{bookId}})
---
{{#each annotations}}
> [!{{{highlightStyle}}}] [{{dateFormat highlightModificationDate "YYYY-MM-DD hh:mm"}}](ibooks://assetid/{{../bookId}}#{{highlightLocation}})
>
> {{{highlight}}}

{{/each}}
```

Making each of your coloured highlights into coloured callouts.

_This one does involve having to make your own custom callouts titled 0, 1, 2, 3, 4, 5_

Sharing my example css anyway:

```css
.callout[data-callout="0"] {--callout-color: 54,152,142; --callout-icon: plane-takeoff;}
.callout[data-callout="1"] {--callout-color: 175,213,151; --callout-icon: plane-takeoff;}
.callout[data-callout="2"] {--callout-color: 181,205,238; --callout-icon: plane-takeoff;}
.callout[data-callout="3"] {--callout-color: 249,213,108; --callout-icon: plane-takeoff;}
.callout[data-callout="4"] {--callout-color: 242,178,188; --callout-icon: plane-takeoff;}
.callout[data-callout="5"] {--callout-color: 214,192,238; --callout-icon: plane-takeoff;}
```
![CShot 2024-09-15 at 13 57 55@2x](https://github.com/user-attachments/assets/cb68661c-5ebe-4e79-84c3-3d4556e1dc6d)

**Reply by bandantonio** [reply]
Awesome! This one looks great!

**Comment by bobsky212** [comment]
Thank to @jun6lee made my own template. Added notes, if there are any.
```css
---
Title: {{{bookTitle}}}
Author: {{{bookAuthor}}}
Annotations: {{{annotations.length}}}
---
Title:  {{{bookTitle}}}
Author: {{{bookAuthor}}}
Link: [Apple Books Link](ibooks://assetid/{{bookId}})


{{#each annotations}}
> [!{{{highlightStyle}}}]
{{{highlight}}}

{{#if note}}Note: {{{note}}}⁣
{{/if}}
*{{dateFormat highlightModificationDate "DD MMMM ′YY · hh:mm"}} · {{#if highlightLocation}}[Show in Books](ibooks://assetid/{{../bookId}}#{{highlightLocation}}){{else}}N/A{{/if}}⁣*
⁣
⁣

{{/each}}
```
Also updated snippet to:
```css
.callout[data-callout="0"] {--callout-color: 54,152,142; --callout-icon: plane-takeoff;}
.callout[data-callout="0"] .callout-title {display: none;}
.callout[data-callout="0"] p {margin: 16px 0px !important;}
.callout[data-callout="1"] {--callout-color: 175,213,151; --callout-icon: plane-takeoff;}
.callout[data-callout="1"] .callout-title {display: none;}
.callout[data-callout="1"] p {margin: 16px 0px !important;}
.callout[data-callout="2"] {--callout-color: 181,205,238; --callout-icon: plane-takeoff;}
.callout[data-callout="2"] .callout-title {display: none;}
.callout[data-callout="2"] p {margin: 16px 0px !important;}
.callout[data-callout="3"] {--callout-color: 249,213,108; --callout-icon: plane-takeoff;}
.callout[data-callout="3"] .callout-title {display: none;}
.callout[data-callout="3"] p {margin: 16px 0px !important;}
.callout[data-callout="4"] {--callout-color: 242,178,188; --callout-icon: plane-takeoff;}
.callout[data-callout="4"] .callout-title {display: none;}
.callout[data-callout="4"] p {margin: 16px 0px !important;}
.callout[data-callout="5"] {--callout-color: 214,192,238; --callout-icon: plane-takeoff;}
.callout[data-callout="5"] .callout-title {display: none;}
.callout[data-callout=""] p {margin: 16px 0px !important;}
```
And here is how it looks
![SCR-20240928-bjzc](https://github.com/user-attachments/assets/71b0daa4-0b7d-4db7-bdc1-ce94f2935290)
